# python-challenge
So as an extra note from me. I used the line of code you sugggested and I stopped outputting it all to a txt file however something strange happened on my machine but I have a feeling it won't happen on yours. Whenever I ran my code it would keep saying that the file did not exist despite me using the code you provided HOWEVER. If I was debugging then suddenly it would run flawlessly and find my csv file. I'm not sure why that was happening but it may be an issue with my machine I believe.
